### ISSUE TITLE
"Circular Reference" in unit tests

### ISSUE THREAD

**Issue by Enturk** [drafter-edu/drafter#26] opened 2024-11-24 15:38 UTC
When complex pages are generated, the unit tests generated by drafter sometimes set an argument's value to "Circular Reference", which then fails when implemented.

![DrafterCircularReference](https://github.com/user-attachments/assets/fdceabe4-9e1b-4ca1-b6ee-a9b9b1749b70)

These are the milestones of one of the students who encountered the problem:
* https://blockpy.cis.udel.edu/blockpy/view_submission?submission_id=1378097&embed=True
* https://blockpy.cis.udel.edu/blockpy/view_submission?submission_id=1387486&embed=True

It would be better if it didn't do this, although I'm uncertain if that's possible.

**Comment by acbart** [comment] 2024-11-24 16:25
This was caused by an error in the `safe_repr` function, which was not correctly backtracking through the tree of data. Specifically, it was not using a copied set when backtracking. This meant that it would end up incorrectly marking elements that appeared more than once. 

I'm pushing a fix for this now, but this also exposed a new issue (#27) with how we are handling *actual* circular references.

**Closed** 2024-11-24 16:46 UTC
